engines:
    apexmetrics:
        enabled:  true
    duplication:
        enabled:  true
    eslint:
        enabled:  true
        checks:
            no-unused-expressions:
                enabled:  false
ratings:
    paths:
        -  "**.cls"
        -  "**.trigger"
